services:
  cup:
    image: ghcr.io/sergi0g/cup:latest
    container_name: cup # Optional
    restart: unless-stopped
    command: -c /config/cup.json serve
    ports:
      - 7129:8000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./cup.json:/config/cup.json
