services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
      - VERSION=docker
    volumes:
      - ./config:/config
      - ${BASE}/library/series:/tv
      - ${BASE}/library/movies:/movies
    restart: unless-stopped
