services:
  searxng:
    image: searxng/searxng
    container_name: searxng
    restart: always
    ports:
      - "3210:8080"
    env_file:
      - .env
    environment:
      - BASE_URL=${BASE_URL}
      - SEARXNG_SETTINGS_PATH=/etc/searxng/settings.yml
    volumes:
      - ./settings.yml:/etc/searxng/settings.yml
    networks:
      - searxng-network

networks:
  searxng-network:
    driver: bridge
