services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginx-proxy-manager
    restart: always
    ports:
      - '2080:80'
      - '2443:443'
      - '2081:81'
    env_file:
      - .env
    volumes:
      - /docker_data/nginx-proxy-manager_data:/data
      - /letsencrypt:/etc/letsencrypt
    depends_on:
      - db

  db:
    image: 'yobasystems/alpine-mariadb:latest'
    restart: always
    env_file:
      - .env
    volumes:
      - /docker_data/mysql-nginx-proxy-manager:/var/lib/mysql
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"

  cloudflare-ddns:
    image: timothyjmiller/cloudflare-ddns:latest
    container_name: cloudflare-ddns
    security_opt:
      - no-new-privileges:true
    network_mode: 'host'
    env_file:
      - .env
    volumes:
      - ${CONFIG_FILE}:/config.json
    restart: unless-stopped

networks:
  default:
    external:
      name: nginx-network
