services:
  agent:
    image: portainer/agent
    container_name: portainer_agent
    restart: always
    networks:
      - portainer_agent_network
    ports:
      - 9001:9001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes

networks:
  portainer_agent_network:
    driver: bridge
